<?php
/*
 * Localization file for ident_switch plugin
 */
$labels = array();

// IMAP
$labels['form.caption'] = 'IMAP';

// Enabled
$labels['form.enabled'] = 'Enabled';

// Label
$labels['form.label'] = 'Label';

// Server host name
$labels['form.host']='Server host name';

// Secure connection (SSL/TLS)
$labels['form.secure']='Secure connection (SSL/TLS)';

// Port
$labels['form.port']='Port';

// Username
$labels['form.username'] = 'Username';

// Passwotrd
$labels['form.password'] = 'Password';

// Folder hierarchy delimiter
$labels['form.delimiter'] = 'Folder hierarchy delimiter';
