<?php
/*
 * Localization file for ident_switch plugin
 */
$labels = array();

// IMAP
$labels['form.caption'] = 'IMAP';

// Enabled
$labels['form.enabled'] = 'Enabled';

// Label
$labels['form.label'] = 'Label';

// Server URI
$labels['form.server']='Server URI';

// Username
$labels['form.username'] = 'Username';

// Passwotrd
$labels['form.password'] = 'Password';

// Folder hierarchy delimiter
$labels['form.delimiter'] = 'Folder hierarchy delimiter';
