<?php
/*
 * Localization file for ident_switch plugin
 */
$labels = array();

// IMAP
$labels['form.caption'] = 'IMAP';

// Enabled
$labels['form.enabled'] = 'Включено';

// Label
$labels['form.label'] = 'Название';

// Server host name
$labels['form.host'] = 'Адрес сервера';

// Secure connection (SSL/TLS)
$labels['form.secure'] = 'Безопасное соединение (SSL/TLS)';

// Port
$labels['form.port'] = 'Порт';

// Username
$labels['form.username'] = 'Имя пользователя';

// Passwotrd
$labels['form.password'] = 'Пароль';

// Folder hierarchy delimiter
$labels['form.delimiter'] = 'Разделитель в иерархии папок';
